### ISSUE TITLE
Respect book.build-dir

### ISSUE THREAD

**Issue by CreepySkeleton** [Michael-F-Bryan/mdbook-linkcheck#23]
I have the following settings:
```toml
[book]
authors = ["CreepySkeleton"]
# ...

[build]
build-dir = "docs/" # I want the docs to be put into docs/ folder instead of book/ 

[output.html]

[output.linkcheck]
# ...
```

unfortunately, this setup does not respect `build-dir`, placing the generated files into `docs/html`. Any way to fix it?
